### PR TITLE
displayed group member and add theme to view group and dashboard

### PR DESCRIPTION
**Pull request by Peiyj**
## Trello Ticket :ticket: ##
https://trello.com/c/wub4X2Kj
https://trello.com/c/r1PmgDQ5
## Summary :chart_with_upwards_trend: ##
The PR fixes the color passing around problem as well as displaying the group members successfully. Now, it is more colorful than ever lol.
## Test plan :clipboard: ##
Visual and backend test from firebase.

### CODE REVIEW

**Comment by danielbang907** [comment]
will review asap

**Review by danielbang907 — COMMENTED** [review]
I can't seem to view any of the test groups; only newly created groups. It seems as though there isn't a view group page made for the test groups, or at least it doesn't route there

**Comment by Peiyj** [comment]
> I can't seem to view any of the test groups; only newly created groups. It seems as though there isn't a view group page made for the test groups, or at least it doesn't route there

I think there is an issue with groupCardComponent that is causing the problem. @jakerogers2022 @tbayvas do you know if there is a fix for this?

**Comment by jakerogers2022** [comment]
> > I can't seem to view any of the test groups; only newly created groups. It seems as though there isn't a view group page made for the test groups, or at least it doesn't route there
> 
> I think there is an issue with groupCardComponent that is causing the problem. @jakerogers2022 @tbayvas do you know if there is a fix for this?

Viewing all the groups is working for me, but I'm getting a different error.
"TypeError: moment().format('YYYY/MM/DD').replaceAll is not a function. (In 'moment().format('YYYY/MM/DD').replaceAll("/", ",")', 'moment().format('YYYY/MM/DD').replaceAll' is undefined)"

**Comment by Peiyj** [comment]
> > > I can't seem to view any of the test groups; only newly created groups. It seems as though there isn't a view group page made for the test groups, or at least it doesn't route there
> > 
> > 
> > I think there is an issue with groupCardComponent that is causing the problem. @jakerogers2022 @tbayvas do you know if there is a fix for this?
> 
> Viewing all the groups is working for me, but I'm getting a different error.
> "TypeError: moment().format('YYYY/MM/DD').replaceAll is not a function. (In 'moment().format('YYYY/MM/DD').replaceAll("/", ",")', 'moment().format('YYYY/MM/DD').replaceAll' is undefined)"

Oh for that, I think you need to do `npm install moment`

**Pull request merged**
